// Generates public/shape-icons/<index>.json, one tiny file per OBJECTS icon (so the game fetches only
// the icons a round needs), plus src/shape-icons.ts with the count and a content hash for cache busting.
// Order and count come from src/shapes.ts, which stays the single source of truth for which icon is
// which daily-puzzle index.
//
//   npx tsx scripts/build-shape-icons.ts   (also runs as part of npm run dev / build)
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { createHash } from 'node:crypto';

const OUT = 'public/shape-icons';
const shapes = readFileSync('src/shapes.ts', 'utf8');
const names = shapes.slice(shapes.indexOf('export const OBJECTS')).match(/\bFa\w+/g)!;
const faSource = readFileSync('node_modules/react-icons/fa/index.mjs', 'utf8');

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT);
const hash = createHash('sha256');
names.forEach((name, i) => {
  const start = faSource.indexOf(`export function ${name} (props) {`);
  if (start < 0) throw new Error(`build-shape-icons: ${name} not found in react-icons/fa`);
  const from = faSource.indexOf('GenIcon(', start) + 'GenIcon('.length;
  const data = faSource.slice(from, faSource.indexOf(')(props);', from));
  JSON.parse(data);
  writeFileSync(`${OUT}/${i}.json`, data);
  hash.update(data);
});
writeFileSync('src/shape-icons.ts', `// Generated by scripts/build-shape-icons.ts. Daily puzzles pick icons as index < SHAPE_COUNT,
// so changing the icon list in src/shapes.ts changes every daily puzzle.
export const SHAPE_COUNT = ${names.length};
export const SHAPE_VERSION = '${hash.digest('hex').slice(0, 10)}';
`);
console.log(`shape icons: ${names.length}`);
