// Splits the flag and crest data into what the daily picker needs (a small index, bundled) and the
// artwork (one SVG per flag/club in public/, fetched only for the day's 4). Same idea as
// build-shape-icons.ts. Index order is the data order, which the daily picks depend on, so it must
// never be re-sorted here.
//
//   npx tsx scripts/build-art.ts   (also runs as part of npm run dev / build)
import { writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { FLAGS_DATA } from '../src/flag/flags-data';
import { CRESTS_DATA } from '../src/crest/crests-data';

type Item = { name: string; code: string; svg: string; hideable: unknown[] };

const split = (items: Item[], dir: string, indexFile: string, constName: string, typeImport: string, typeName: string) => {
  rmSync(`public/${dir}`, { recursive: true, force: true });
  mkdirSync(`public/${dir}`);
  const seen = new Set<string>();
  const index = items.map(({ svg, ...meta }) => {
    if (!/^[A-Za-z0-9_-]+$/.test(meta.code) || seen.has(meta.code.toLowerCase())) throw new Error(`build-art: bad or duplicate code "${meta.code}" in ${dir}`);
    seen.add(meta.code.toLowerCase());
    writeFileSync(`public/${dir}/${meta.code}.svg`, svg);
    // Per-file version: a redrawn flag busts only its own cache entry.
    return { ...meta, v: createHash('sha256').update(svg).digest('hex').slice(0, 8) };
  });
  writeFileSync(indexFile, `// Generated by scripts/build-art.ts from ${typeImport.split('/').pop()}. Order matters: daily picks index into it.
import type { ${typeName} } from '${typeImport}';
export const ART_DIR = '/${dir}';
export const ${constName}: (Omit<${typeName}, 'svg'> & { v: string })[] = ${JSON.stringify(index)};
`);
  return index.length;
};

const flags = split(FLAGS_DATA, 'flag-art', 'src/flag/flags-index.ts', 'FLAGS_INDEX', './flags-data', 'FlagData');
const crests = split(CRESTS_DATA, 'crest-art', 'src/crest/crests-index.ts', 'CRESTS_INDEX', './crests-data', 'CrestData');
console.log(`art: ${flags} flags, ${crests} crests`);
